### ISSUE TITLE
hide avatar feature

### ISSUE THREAD

**Issue by shivanshu-semwal** [vednoc/dark-whatsapp#197]
**Describe the change you'd like**: hide avatar feature, also a grayscale filter if someone wants that

**Additional context**: i don't like profile images, it's distracting

here is how i do this by using additional stylesheet

```css
._1AHcd{
    display: none;
}

._8nE1Y{
    padding-left: 20px;
}
```
